### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by lequan81** [cheprogrammer/liquid_crystal_i2c_avr#3]
Hi denisgoriachev,
thank you so much for your library. It is very great. But when I follow your instructions, I get this error(s).

1. I open Arduino IDE and start a new project
2. I copied all your file(s) (liquid_crystal_i2c.h, liquid_crystal_i2c.c, i2c_master.h, i2c_master.c)
3. I write a code like this, please correct if I wrong.  (https://pastebin.com/raw/1agAgctL)
    
#define F_CPU 160000000 // 16 MHz
#include <avr/io.h>
#include <util/delay.h>
#include "liquid_crystal_i2c.h"

int main(void) {
  LiquidCrystalDevice_t device = lq_init(0x27, 20, 4, LCD_5x8DOTS); // intialize 4-lines display

lq_turnOnBacklight(&device); // simply turning on the backlight

lq_print(&device, "Hello world!");
lq_setCursor(&device, 1, 0); // moving cursor to the next line
lq_print(&device, "How are you?");
}

4. Then it gave me this error(s) message:
 "Arduino: 1.8.15 (Windows 10), Board: "Arduino Uno"

sketch\liquid_crystal_i2c.c.o (symbol from plugin): In function `i2c_getErrorMessage':

(.text+0x0): multiple definition of `i2c_getErrorMessage'

sketch\i2c_master.c.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\**\AppData\Local\Temp\ccKOLEcc.ltrans0.ltrans.o: In function `main':

C:\Users\**\Desktop\Test-i2c/Test-i2c.ino:9: undefined reference to `lq_init(unsigned char, unsigned char, unsigned char, unsigned char)'

C:\Users\**\Desktop\Test-i2c/Test-i2c.ino:11: undefined reference to `lq_turnOnBacklight(LiquidCrystalDevice_t*)'

C:\Users\**\Desktop\Test-i2c/Test-i2c.ino:13: undefined reference to `lq_print(LiquidCrystalDevice_t*, char*)'

C:\Users\**\Desktop\Test-i2c/Test-i2c.ino:14: undefined reference to `lq_setCursor(LiquidCrystalDevice_t*, unsigned char, unsigned char)'

C:\Users\**\Desktop\Test-i2c/Test-i2c.ino:15: undefined reference to `lq_print(LiquidCrystalDevice_t*, char*)'

collect2.exe: error: ld returned 1 exit status

exit status 1

Error compiling for board Arduino Uno."

So I wonder that maybe I miss-understand something in your instruction. Could you spot that for me?

Thank you so much. Have a nice day.

**Comment by denisgoriachev** [comment]
Hi @lequan81! Its been a while since I last time used this library - to be honest, I almost forgot everything about MCU programming 😅 Sorry, cant help you with that.... But it seems that something is wrong with importing i2c definitions.

**Comment by lequan81** [comment]
Thank you for your reply. Well I tried to programing just using avrdude and it work 😃  (with main.c file and import .hex file created by main.c file into ATmega328p).

So I guess that the problem is the Arduino IDE itself. 🥲
